import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Drops',
      link: { type: 'doc', id: 'drops/index' },
      items: [
        // {
        //   type: 'category',
        //   label: 'Emails',
        //   items: [{ type: 'autogenerated', dirName: 'drops/emails' }],
        // },
        // {
        //   type: 'category',
        //   label: 'Memos',
        //   items: [{ type: 'autogenerated', dirName: 'drops/memos' }],
        // },
        // {
        //   type: 'category',
        //   label: 'Reports',
        //   items: [{ type: 'autogenerated', dirName: 'drops/reports' }],
        // },
        {
          type: 'category',
          label: 'Chat Logs',
          items: [{ type: 'autogenerated', dirName: 'drops/chat-logs' }],
        },
        // {
        //   type: 'category',
        //   label: 'Whitepapers',
        //   items: [{ type: 'autogenerated', dirName: 'drops/whitepapers' }],
        // },
        // {
        //   type: 'category',
        //   label: 'Field Notes',
        //   items: [{ type: 'autogenerated', dirName: 'drops/field-notes' }],
        // },
        // {
        //   type: 'category',
        //   label: 'Directives',
        //   items: [{ type: 'autogenerated', dirName: 'drops/directives' }],
        // },
        // {
        //   type: 'category',
        //   label: 'Case Files',
        //   items: [{ type: 'autogenerated', dirName: 'drops/case-files' }],
        // },
        // {
        //   type: 'category',
        //   label: 'Protocols',
        //   items: [{ type: 'autogenerated', dirName: 'drops/protocols' }],
        // },
        // {
        //   type: 'category',
        //   label: 'Artifacts',
        //   items: [{ type: 'autogenerated', dirName: 'drops/artifacts' }],
        // },
      ],
    },
  ],
};

export default sidebars;
